# This is a file for you to write an un-named mutation. 
# Only one un-named mutation is allowed per file.
mutation {
  user_insert(
    data: {email: "teast1email@gmail.com", id: "11111111222233334444555555555555", username: "DM"}
  )
}